
package clientews;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioEncuestaImplService", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", wsdlLocation = "http://www.lynx.pruebas:8080/ServicioEncuestaImplService/ServicioEncuestaImpl?WSDL")
public class ServicioEncuestaImplService
    extends Service
{

    private final static URL SERVICIOENCUESTAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOENCUESTAIMPLSERVICE_EXCEPTION;
    private final static QName SERVICIOENCUESTAIMPLSERVICE_QNAME = new QName("http://servicios.sistemasatisfaccionws.lynx.com/", "ServicioEncuestaImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.lynx.pruebas:8080/ServicioEncuestaImplService/ServicioEncuestaImpl?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOENCUESTAIMPLSERVICE_WSDL_LOCATION = url;
        SERVICIOENCUESTAIMPLSERVICE_EXCEPTION = e;
    }

    public ServicioEncuestaImplService() {
        super(__getWsdlLocation(), SERVICIOENCUESTAIMPLSERVICE_QNAME);
    }

    public ServicioEncuestaImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOENCUESTAIMPLSERVICE_QNAME, features);
    }

    public ServicioEncuestaImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOENCUESTAIMPLSERVICE_QNAME);
    }

    public ServicioEncuestaImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOENCUESTAIMPLSERVICE_QNAME, features);
    }

    public ServicioEncuestaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioEncuestaImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioEncuesta
     */
    @WebEndpoint(name = "ServicioEncuestaImplPort")
    public ServicioEncuesta getServicioEncuestaImplPort() {
        return super.getPort(new QName("http://servicios.sistemasatisfaccionws.lynx.com/", "ServicioEncuestaImplPort"), ServicioEncuesta.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioEncuesta
     */
    @WebEndpoint(name = "ServicioEncuestaImplPort")
    public ServicioEncuesta getServicioEncuestaImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios.sistemasatisfaccionws.lynx.com/", "ServicioEncuestaImplPort"), ServicioEncuesta.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOENCUESTAIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICIOENCUESTAIMPLSERVICE_EXCEPTION;
        }
        return SERVICIOENCUESTAIMPLSERVICE_WSDL_LOCATION;
    }

}
