
package clientews;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioEncuesta", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioEncuesta {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarCredenciales", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.ValidarCredenciales")
    @ResponseWrapper(localName = "validarCredencialesResponse", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.ValidarCredencialesResponse")
    @Action(input = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/validarCredencialesRequest", output = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/validarCredencialesResponse")
    public int validarCredenciales(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mostrarNivelesDeSatisfaccion", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.MostrarNivelesDeSatisfaccion")
    @ResponseWrapper(localName = "mostrarNivelesDeSatisfaccionResponse", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.MostrarNivelesDeSatisfaccionResponse")
    @Action(input = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/mostrarNivelesDeSatisfaccionRequest", output = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/mostrarNivelesDeSatisfaccionResponse")
    public List<Integer> mostrarNivelesDeSatisfaccion();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarUsuario", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.RegistrarUsuario")
    @ResponseWrapper(localName = "registrarUsuarioResponse", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.RegistrarUsuarioResponse")
    @Action(input = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/registrarUsuarioRequest", output = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/registrarUsuarioResponse")
    public String registrarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "acualizarUsuario", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.AcualizarUsuario")
    @ResponseWrapper(localName = "acualizarUsuarioResponse", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.AcualizarUsuarioResponse")
    @Action(input = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/acualizarUsuarioRequest", output = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/acualizarUsuarioResponse")
    public String acualizarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarUsuario", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.EliminarUsuario")
    @ResponseWrapper(localName = "eliminarUsuarioResponse", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.EliminarUsuarioResponse")
    @Action(input = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/eliminarUsuarioRequest", output = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/eliminarUsuarioResponse")
    public String eliminarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clientews.UsuarioDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarUsuarios", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.ListarUsuarios")
    @ResponseWrapper(localName = "listarUsuariosResponse", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.ListarUsuariosResponse")
    @Action(input = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/listarUsuariosRequest", output = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/listarUsuariosResponse")
    public List<UsuarioDTO> listarUsuarios();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "aplicarEncuesta", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.AplicarEncuesta")
    @ResponseWrapper(localName = "aplicarEncuestaResponse", targetNamespace = "http://servicios.sistemasatisfaccionws.lynx.com/", className = "clientews.AplicarEncuestaResponse")
    @Action(input = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/aplicarEncuestaRequest", output = "http://servicios.sistemasatisfaccionws.lynx.com/ServicioEncuesta/aplicarEncuestaResponse")
    public String aplicarEncuesta(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
